# -*- coding: utf-8 -*-
"""07_pytorch_optimizers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YyCDyfcFn6yOFMFx1hBZM0LcghRz9uPZ
"""

import torch                      # the main PyTorch library
import torch.nn as nn             # nn = neural network building blocks
import torch.optim as optim       # optim = optimizers (SGD, Adam, etc.)
import matplotlib.pyplot as plt

# Set seed for reproducible results
torch.manual_seed(42)

# Our student data — now as PyTorch "tensors" instead of NumPy arrays
# A tensor is just like a NumPy array, but PyTorch can track gradients on it!
X = torch.tensor([
    [2.0, 7.0],   # Student A
    [5.0, 6.0],   # Student B
    [8.0, 5.0],   # Student C
    [1.0, 4.0]    # Student D
])

y = torch.tensor([
    [0.0],   # A: fail
    [1.0],   # B: pass
    [1.0],   # C: pass
    [0.0]    # D: fail
])

# Normalize (same as before — subtract mean, divide by std)
X = (X - X.mean(dim=0)) / X.std(dim=0)

print("Data ready! X shape:", X.shape)

# Define our network as a class (a blueprint)
class StudentNet(nn.Module):
    def __init__(self):
        super().__init__()
        # nn.Linear(inputs, outputs) creates a layer with weights + biases AUTOMATICALLY!
        # It even initializes them with good random values for us!
        self.hidden = nn.Linear(2, 2)   # 2 inputs → 2 hidden neurons
        self.output = nn.Linear(2, 1)   # 2 hidden → 1 output

    def forward(self, x):
        # This describes the forward pass
        x = torch.relu(self.hidden(x))  # hidden layer + ReLU
        x = torch.sigmoid(self.output(x))  # output layer + Sigmoid
        return x

# Create the network
model = StudentNet()
print(model)

# Loss function: Binary Cross-Entropy (same as Project #1!)
criterion = nn.BCELoss()

# Optimizer: this does the weight updates for us
# We'll start with plain SGD (stochastic gradient descent)
optimizer = optim.SGD(model.parameters(), lr=0.5)

print("Loss function:", criterion)
print("Optimizer:", optimizer)

epochs = 1000
loss_history = []

for epoch in range(epochs):
    # Step 1: Forward pass
    y_pred = model(X)

    # Step 2: Calculate loss
    loss = criterion(y_pred, y)
    loss_history.append(loss.item())

    # Step 3: Backward pass (backprop) — PyTorch does it AUTOMATICALLY!
    optimizer.zero_grad()   # clear old gradients first
    loss.backward()         # compute all gradients (the chain rule, automatic!)

    # Step 4: Update weights
    optimizer.step()        # apply the update rule to all weights

    if epoch % 100 == 0:
        print(f"Epoch {epoch:4d} | Loss: {loss.item():.4f}")

print(f"\nFinal loss: {loss_history[-1]:.4f}")

# Plain SGD (what we used)
optimizer = optim.SGD(model.parameters(), lr=0.5)

# SGD with Momentum (just add momentum=)
optimizer = optim.SGD(model.parameters(), lr=0.5, momentum=0.9)

# RMSprop
optimizer = optim.RMSprop(model.parameters(), lr=0.01)

# Adam (the popular one!)
optimizer = optim.Adam(model.parameters(), lr=0.001)

