# -*- coding: utf-8 -*-
"""08_Overfitting_and_regularisation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f1Uf7-gc25luJ_Z_U57R9KrThvsM9rUE
"""

import torch
import torch.nn as nn
import torch.optim as optim

class StudentNetWithDropout(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(2, 8)      # bigger hidden layer (8 neurons)
        self.dropout = nn.Dropout(0.3)     # drop 30% of neurons during training
        self.output = nn.Linear(8, 1)

    def forward(self, x):
        x = torch.relu(self.hidden(x))
        x = self.dropout(x)                # apply dropout AFTER activation
        x = torch.sigmoid(self.output(x))
        return x

model = StudentNetWithDropout()
print(model)

# weight_decay adds the L2 penalty automatically
optimizer = optim.Adam(model.parameters(), lr=0.01, weight_decay=0.0001)

model.train()   # training mode: dropout is ON (neurons randomly dropped)
model.eval()    # evaluation mode: dropout is OFF (all neurons active)

best_val_loss = float('inf')   # start with "infinity" as worst
patience = 10                   # wait 10 epochs for improvement
epochs_without_improvement = 0

for epoch in range(1000):
    # ... training code (forward, loss, backward, step) ...

    # check validation loss
    model.eval()
    with torch.no_grad():
        val_pred = model(X_val)
        val_loss = criterion(val_pred, y_val).item()
    model.train()

    # is this the best so far?
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        epochs_without_improvement = 0   # reset counter
    else:
        epochs_without_improvement += 1

    # stop if no improvement for 'patience' epochs
    if epochs_without_improvement >= patience:
        print(f"Early stopping at epoch {epoch}!")
        break

